name: CI/CD Docker Deployment - Production

on:
  push:
    branches:
      - test

jobs:
  build_and_push_to_ecr:
    runs-on: ubuntu-latest

    steps:
    #   - name: Set up JDK 17
    #     uses: actions/setup-java@v2
    #     with:
    #       java-version: '17'
    #       distribution: 'temurin'

    #   - name: Checkout Common Platform Repository
    #     uses: actions/checkout@v4
    #     with:
    #       repository: gambitcyberorg/common-platform
    #       ref: production
    #       ssh-key: ${{ secrets.SECRET_KEY_COMMON_PLATFORM }}

    #   - name: Build Dependency with Maven
    #     run: |
    #       mvn -B clean install -Dmaven.test.skip=true || (echo "Dependency build failed" && exit 1)

      - name: Checkout Main Repository
        uses: actions/checkout@v2

    #   - name: Build with Maven
    #     run: |
    #       mvn -B package --file pom.xml -Dmaven.test.skip=true   

    #   - name: Configure AWS Credentials
    #     uses: aws-actions/configure-aws-credentials@v2
    #     with:
    #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
    #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
    #       aws-region: ${{ secrets.AWS_REGION_PROD }}

    #   - name: Login to Amazon ECR
    #     uses: aws-actions/amazon-ecr-login@v1

    #   - name: Build Docker Image
    #     run: |
    #        ECR_REPOSITORY_NAME="tid-prod"
    #        docker build --tag tid-prod:latest -f Dockerfile-prod .

    #   - name: Tag and Push Docker Image
    #     run: |
    #        docker tag tid-prod:latest ${{ secrets.AWS_ACCOUNT_ID_PROD }}.dkr.ecr.${{ secrets.AWS_REGION_PROD }}.amazonaws.com/tid-prod:latest
    #        docker push ${{ secrets.AWS_ACCOUNT_ID_PROD }}.dkr.ecr.${{ secrets.AWS_REGION_PROD }}.amazonaws.com/tid-prod:latest

    #   - name: Login to Amazon ECR India environment
    #     uses: aws-actions/amazon-ecr-login@v1
    #     env:
    #       AWS_REGION: ap-south-1

    #   - name: Build Docker Image India environment
    #     run: |
    #       ECR_REPOSITORY_NAME="tid-prod-india"
    #       docker build --tag tid-prod-india:latest -f Dockerfile-ind .

    #   - name: Tag and Push Docker Image India environment
    #     run: |
    #       docker tag tid-prod-india:latest ${{ secrets.AWS_ACCOUNT_ID_PROD }}.dkr.ecr.ap-south-1.amazonaws.com/tid-prod-india:latest
    #       docker push ${{ secrets.AWS_ACCOUNT_ID_PROD }}.dkr.ecr.ap-south-1.amazonaws.com/tid-prod-india:latest

 # GCP ARTIFACT REGISTRY            
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
            credentials_json: ${{ secrets.GCP_SA_KEY }}   

      - name: Test auth
        run: |
            gcloud auth list

      - name: Set GCP project
        run: |
            gcloud config set project ${{secrets.GCP_PROJECT_ID}}
            
      - name: Configure Docker for Artifact Registry
        run: |
            gcloud auth configure-docker ${{secrets.GCP_REGION_PROD}}-docker.pkg.dev --quiet     
      - name: Build Docker Image
        run: |
          docker build -t tid-prod:latest .
          
      - name: Tag & Push Docker Image to GCP Artifact Registry
        run: |
          GCP_IMAGE="${{secrets.GCP_REGION_PROD}}-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/tid-prod/tid-prod:latest"

          docker tag tid-prod:latest $GCP_IMAGE
          docker push $GCP_IMAGE      

      